# Generated by Django 6.0.1 on 2026-01-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobLink', '0002_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
